### ISSUE TITLE
Reporting errors in fastapi repeating functions

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-python#118]
This is a bug report from a past user. @Kelvin4664 @subzero10 could we automatically report errors in this case? Or would it be better to manually try/catch the error in the function (and if so, can we update the docs)?

> In FastAPI, I run functions every 60 seconds using the building mechanism in fastapi like this:
>
> ```python
> app = FastAPI()
> @app.on_event("startup")
> @repeat_every(seconds=60)
> def every_minute_sync_job() -> None:
>     # Do stuff
>     pass
> ```
> 
> 
> I want to catch the exceptions that occur in the every_minute_sync_job() function.
> I think it creates a separate thread for those, and therefore it doesn't seem to catch those.
> The docs i saw from honeybadger seemed to be specifically for api call and not for the repeated functions that i use.

**Comment by joshuap** [comment]
Here's some additional feedback:

> I later found that the function has some optional arguments that may help in this case : "raise_exceptions" and "logger".
https://fastapi-utils.davidmontague.xyz/user-guide/repeated-tasks/
>
> I didn't had time to test it with Honeybadger.

**Comment by Kelvin4664** [comment]
I did some digging into this one, Including the source code for fastapi_utils.
The default behaviour is for errors to fail silently (And they don't get reported to honeybadger since these exceptions are caught by fastapi_utils)
And indeed, there's an argument to change this behaviour by setting raise_exceptions to True and providing a logger.
Honeybadger already provides a log handler that can be configured for this purpose.
