### ISSUE TITLE
upside-down logic in Django tests

### ISSUE THREAD

**Issue by dotysan** [honeybadger-io/honeybadger-python#147]
What is the purpose of this?

https://github.com/honeybadger-io/honeybadger-python/blob/65215a97318bda878c8b23bbf64e5ff6cf3fd854/honeybadger/tests/contrib/test_django.py#L32-L45

It appears to be both unmaintained and upside-down.

For example, on Python 3.9 with any current Django LTS release, it will skip 3 tests that I belive it should be running. I.e. disabling the `@unittest.skipUnless(versions_match())` decorator and the tests still pass just fine.

Clearly I'm missing something. Because just removing the above, and any invalid paring of Python/Django versions should still generate their own errors.

**Comment by subzero10** [comment]
> What is the purpose of this?

I guess it was created because some tests are not supposed to run with all version combinations of Django and Python.

> It appears to be both unmaintained and upside-down.
>
> For example, on Python 3.9 with any current Django LTS release, it will skip 3 tests that I belive it should be running. I.e. disabling the @unittest.skipUnless(versions_match()) decorator and the tests still pass just fine.

Indeed, this seems to be outdated and from a first guess it should at least list the Django versions we test against in CI workflow. Right now it's missing `3.2` and `4.2`, these are the current LTS releases you are referring to right?
