### ISSUE TITLE
Register Lambda plugin automatically?

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-python#69]
@Kelvin4664 Would it be possible to detect the AWS Lambda environment and register the Lambda plugin automatically, so that the user can skip doing [this](https://github.com/honeybadger-io/honeybadger-python/blob/master/examples/aws_lambda/handler.py#L6)?

**Comment by joshuap** [comment]
A few ideas of where we could do this:

- When importing `honeybadger`
- When calling `honeybadger.configure`

**Comment by joshuap** [comment]
Let me know if this is a bad idea or if the explicit registration is more conventional in Python.

**Comment by Kelvin4664** [comment]
The current plugin setup doesn't allow us register a plugin from the configuration class without creating circular imports. but a fix can be worked since we're already refactoring the plugin system in #68 
And yeah i agree it should be auto detected when honeybadger.configure is called. since honeybadger may just be imported and unused.
