### ISSUE TITLE
Should we be able to combine payloads from different plugins?

### ISSUE THREAD

**Issue by Kelvin4664** [honeybadger-io/honeybadger-python#77]
There's a possible scenario where we have more than one plugin registered at a time.
E.g: I have a django/flask application deployed to AWS Lambda. This makes it possible to have the lambda plugin auto registered & possibly the flask/django plugin (if used on the application.)
Current behaviour is to return payload from the first registered plugin.
Proposed behaviour is to pass the payload through all registered plugins before returning.
@joshuap any thoughts?

**Comment by joshuap** [comment]
@Kelvin4664 I like that idea. It would be nice if multiple plugins could be used at once. 👍

**Comment by stefanondisponibile** [comment]
What merge style would you expect?
Like, having a [key for each plugin](https://github.com/honeybadger-io/honeybadger-python/blob/04a99bbf7c654c14b5a008182a0ce8f8b5039aea/honeybadger/plugins.py#L69)?

**Comment by joshuap** [comment]
> What merge style would you expect?
> Like, having a [key for each plugin](https://github.com/honeybadger-io/honeybadger-python/blob/04a99bbf7c654c14b5a008182a0ce8f8b5039aea/honeybadger/plugins.py#L69)?

I imagine we'd want to be able to register multiple plugins, and then the generated payloads for each plugin should be merged with each other to generate the final payload. Here's an example of what I'd personally expect:

plugin 1:
```
{
  "request": {
    "context": {
      "foo": "foo value"
    }
  }
}
```

plugin 2:
```
{
  "request": {
    "context": {
      "bar": "bar value"
    }
  }
}
```

result:
```
{
  "request": {
    "context": {
      "foo": "foo value",
      "bar": "bar value"
    }
  }
}
```

Our [payload schema](https://github.com/honeybadger-io/honeybadger-schemas/blob/master/exceptions/v1/notices.json#L339) provides an example of what properties should be supported. I wouldn't want to merge objects in user-provided values; for instance:

plugin 1:
```
{
  "request": {
    "context": {
      "myObject": {
        "foo": "foo value"
      }
    }
  }
}
```

plugin 2:
```
{
  "request": {
    "context": {
      "myObject": {
        "bar": "bar value"
      }
    }
  }
}
```

result:
```
{
  "request": {
    "context": {
      "myObject": {
        "bar": "bar value"
      }
    }
  }
}
```

We may want a way to register plugins in order (so that we can determine the merge priority), although it could just be the order in which the plugins were registered.

@Kelvin4664 what do you think?

**Comment by Kelvin4664** [comment]
Apologies.. I didn't catchup with this conversation on time.
Already did something in #81
